debug = false
secret = "__SECRET__"
bind-to = "0.0.0.0:443"
concurrency = 1024
prefer-ip = "prefer-ipv4"
auto-update = false
tolerate-time-skewness = "5s"

[defense.anti-replay]
enabled = true

[defense.blocklist]
enabled = false

[stats.prometheus]
enabled = false
